import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import InstallationComponent from '@/screen/Installation'

export default function Home({ sideBarMenuData }: any) {

  return (
    <>
      <Head>
        <title>Front End Component Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>

      <main className={styles.main}>
        <InstallationComponent />
      </main>
    </>
  )
}



// export async function getStaticProps() {

//   return {
//     props: {
//       sideBarMenuData: sideBarMenuDataJSON
//     }
//   }

// }
// export const config = {
//   runtime: 'experimental-edge',
// }